config/routes.rb
Rails.application.routes.draw do

  root to: "posts#index"
  get "signups/new", to: "registrations#new", as: "new_signup"
  post "signups", to: "registrations#create", as: "signups"

  get "login", to: "logins#new", as: "login"
  post "login", to: "logins#create"
  delete "login", to: "logins#destroy"

  get "posts/new", to: "posts#new", as: "posts_new"
  post "posts", to: "posts#create"
  get "posts/:id/edit", to: "posts#edit", as: "edit_post"
  put "posts/:id", to: "posts#update", as: "post"
  get "posts/:id", to: "posts#show"
  delete "posts/:id", to: "posts#destroy"

  post "posts/:id/comments", to: "comments#create", as: "post_comments"
  delete "posts/:id/comments/:comment_id", to: "comments#destroy", as: "comment"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :email
  
  validates :email, format: {
              with: /.+@.+\..+/,  message: "Must have an @ symbol and a period."
            }
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    user_id = session[:user_id]
    if user_id
      User.find_by(id: user_id)
    end
  end

  def authenticate!
    unless current_user
      flash[:notice] = "You must be logged in in order to do this."
      redirect_to :root
    end
  end

  rescue_from ActiveRecord::RecordNotFound do |e|
    flash[:notice] = "Couldn't find the requested object in the databse.
                           Is your input correct?"
    redirect_to :root
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate!
  def create
    @post = Post.find(params["id"])
    @post.comments.create(body: params["body"],
                          user_id: current_user.id )
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params["id"])
#    binding.pry
    @comment = Comment.find(params["comment_id"])
    @comment.destroy
#    @post.comments.find(params["comment_id"]).destroy
#    @post.comments.find_by(id: params["comment_id"]).destroy
    redirect_to :root
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find(email: params["email"])
    # @user will be nil
    # if @user.authenticate nil does not have a authenticate method
    # throws ActiveRecord::RecordNotFound
    if @user.authenticate(params["password"])
      session[:user_id] = @user.id
      flash[:notice] = "You are now logged in."
      redirect_to :root
    else
      flash[:notice] = "Could not find matching username and password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate!, except: [:show, :index]

  def index
    @posts = Post.all
    render :index
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = current_user.posts.new(title: params["title"],
                                   link: params["link"])
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    authenticate!
    post = Post.find(params["id"])
    render :edit, locals: { post: post }
  end

  def update
    post = Post.find(params["id"])
    post.update(title: params["title"],
                link: params["content"])
    redirect_to :root
  end

  def destroy
    post = Post.find(params["id"])
    if current_user.id == post.user_id
      post.destroy
    else
      flash[:notice] = "You don't have permission for this."
    end

    redirect_to :root
  end

  def show
    @post = Post.find(params["id"])
    render :show
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController <ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(first_name: params["first"],
                     last_name: params["last"],
                     email: params["email"],
                     password: params["password"])
    if @user.save
      redirect_to :root
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myreddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
      <div class="nav-wrapper">
        <a href="" class="brand-logo center">MyReddit</a>

        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if current_user %>
            <h4>Hi there, <%= current_user.first_name %>!</h4>
            <h4><%= link_to("Logout", login_path, method: :delete) %></h4>
            <% else %>
            <h4><%= link_to("Signup", new_signup_path) %><h4>
            <h4><%= link_to("Login", login_path) %></h4>
            <% end %>
        </ul>
      </div>
    </nav>

  <% if flash[:notice] %>
      <h3 class="alert"><%= flash[:notice] %></h3>
  <% end %>

<%= yield %>

</body>
</html>

app/views/logins/new.html.erb
<h2>Login</h2>

<%= form_tag(login_path) do %>
    <div class="login-field">
        <%= label_tag("Email") %>
        <%= text_field_tag("email") %>
    </div>

    <div class="login-field">
        <%= label_tag("Password") %>
        <%= password_field_tag("password") %>
    </div>

    <%= button_tag("Submit") %>
<% end %>

<%= link_to("Return to Homepage", root_path) %>

app/views/posts/_post.html.erb
<h2 class="post-title"><%= post.title %></h2>
<div class="post-body">
     <a target="_blank" href="<%= post.link %>">Click Me</a>
 </div>
 <h4 class="post-date">Written <%= time_ago_in_words(post.created_at) %> ago
 by <%= post.user.first_name%></h4>
 

app/views/posts/edit.html.erb
<%=  form_tag(post_path(post), method: :put) do %>
    <div class="post-field">
        <%= label_tag("Title: ") %> <br/>
        <%= text_field_tag("title", post.title) %>
    </div>

    <div class="post-field">
        <%= label_tag("Content: ") %> <br/>
        <%= text_area_tag("content", post.link) %>
    </div>

    <%= button_tag("Update Post!") %>
<% end %>

app/views/posts/index.html.erb
<%if current_user%>
<%= link_to("Add a New Post!", posts_new_path) %>
<%end%>

<h1>MyReddit Postings</h1>

<ul class="posts">
  <% @posts.each do |post| %>
      <li class="post">
        <%= render partial: "post", locals: { post: post } %>
        <% if current_user && current_user.id == post.user.id%>
        <%= link_to("Edit Post", edit_post_path(post)) %>
        <%= link_to("Delete Post", post_path(post), method: :delete) %>
        <% end %>
      </li>
      <ul class="comment-title">
        <%if current_user%>
        <%=link_to_unless_current("Add a Comment",post_path(post))%>
        <%end%></ul>
        <div class="comments">
          <% post.comments.each do |comment| %>
              <li class="post-comment">
                  <%= simple_format(comment.body) %>
                  <%if current_user && current_user.id == comment.user_id%>
                  <%=link_to("Delete",comment_path(post, comment), method: :delete)%>
                  <%end%>
              </li>
          <% end %>
        </div>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%=  form_tag(posts_path) do %>
    <div class="post-field">
        <%= label_tag("Title: ") %> <br/>
        <%= text_field_tag("title", @post.title) %>
    </div>

    <div class="post-field">
        <%= label_tag("Url: ") %> <br/>
        <%= text_area_tag("link", @post.link) %>
    </div>

    <%= button_tag("Create Post!") %>
<% end %>

app/views/posts/show.html.erb
<nav>
    <br/>
    <%= link_to("Homepage", :root) %>
    <br/>
</nav>

<%= render partial: "post", locals: { post: @post } %>

<div class="comments-form">
    <h3>Add a Comment</h3>
    <%= form_tag(post_comments_path(@post.id)) do %>
      <div class="comment-field">
          <%= text_area_tag("body", nil, cols: 40, rows: 8) %>
      </div>

      <%= button_tag("Create Comment!") %>
    <% end %>
</div>

<h3>Comments</h3>
<div class="comments">
  <% @post.comments.each do |comment| %>
      <div class="post-comment">
          <%= simple_format(comment.body) %>
      </div>
  <% end %>
</div>